### ISSUE TITLE
An error in tcam_line_array

### ISSUE THREAD

**Issue by zheliatakuna** [mcjtag/tcam#2]
Hey, I find an error in tcam_line_array.v, that the mem width don't need to be 2**ADDR_WIDTH, the higher ADDR_WIDTH bits aren't used. and the key, xmask active match all don't need to be 2**ADDR_WIDTH

**Comment by zheliatakuna** [comment]
I have another question. The line_array can only be built with register arrays, which will consume a log of resources. For example, for a 32 bits IP address, if we need to use 20 IP address with mask, then the register number would be 2\*32\*20 = 1280, which is very large. Can we build the tcam with RAM in another way?

**Comment by mcjtag** [comment]
> Hey, I find an error in tcam_line_array.v, that the mem width don't need to be 2**ADDR_WIDTH, the higher ADDR_WIDTH bits aren't used. and the key, xmask active match all don't need to be 2**ADDR_WIDTH

It's not a mistake. ADDR_WIDTH defines a memory depth. If ADDR_WIDTH equals 4, then you can store in memory up to 16 DATA_WIDTH-bit values. Thus, line: `wire [KEY_WIDTH-1:0]key[2**ADDR_WIDTH-1:0]` means that key is a memory for the "KEY", its width is KEY_WIDTH and depth is 2**ADDR_WIDTH (number of stored keys).

**Comment by mcjtag** [comment]
> I have another question. The line_array can only be built with register arrays, which will consume a log of resources. For example, for a 32 bits IP address, if we need to use 20 IP address with mask, then the register number would be 2*32*20 = 1280, which is very large. Can we build the tcam with RAM in another way?

No, I suppose. CAM needs parrallel match output. With RAM it's more like hash table.
